version: '3.1'
services:
    postgres:
        image: postgres:11
        ports:
            - '5432:5432'
        environment:
            - POSTGRES_DB=gate
            - POSTGRES_USER=gate
            - POSTGRES_PASSWORD=gate
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: