name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [1, 2, 3, 4]
    steps:
      - shell: bash
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "secret ${{ matrix.version }} ${{ secrets.API_KEY }} ${{ API_KEY }}"
      - run: echo "${{ matrix.version }} 🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "${{ matrix.version }} 🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "${{ matrix.version }} 🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "${{ matrix.version }} 💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "${{ matrix.version }} 🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "${{ matrix.version }} 🍏 This job's status is ${{ job.status }}."